apiVersion: v1
kind: Service
metadata:
    name: task-k8s
    labels:
        app: task-k8s
spec:
    ports:
    - port: 80
      targetPort: 8081
    selector:
      app: task-k8s
      tier: task-k8s
    type: LoadBalancer
